import Automation from "@/models/Automation";
import Notification from "@/models/Notification";
import Task from "@/models/Task";
import User from "@/models/User";
import { Types } from "mongoose";

export async function runAutomations(userId: string | Types.ObjectId, triggerEvent: string, payload?: any) {
  try {
    const automations = await Automation.find({ userId, trigger: triggerEvent as any, isActive: true });
    
    if (automations.length === 0) return;

    const user = await User.findById(userId).select("email notificationPreferences");

    for (const auto of automations) {
      for (const action of auto.actions) {
        if (action === "create_task") {
          await Task.create({
            userId,
            title: `Automated Task from "${auto.name}"`,
            description: `This task was automatically generated because ${triggerEvent} happened.`,
            status: "todo",
            priority: "medium",
            deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7), // 1 week
          });
        }
        
        if (action === "notify_team") {
          await Notification.create({
            userId,
            title: `Automation Triggered: ${auto.name}`,
            message: `Event "${triggerEvent}" triggered this notification.`,
            type: "system",
            read: false,
          });
        }
        
        if (action === "generate_report") {
          // Mock generating a report by sending a specialized notification or creating a document
          await Notification.create({
            userId,
            title: `Report Generated`,
            message: `A report was generated by automation "${auto.name}".`,
            type: "system",
            read: false,
          });
        }
        
        if (action === "send_email") {
          // Log email to notifications or console if email service not hooked up
          if (user?.notificationPreferences?.statusUpdates) {
            console.log(`[EMAIL MOCK] Sent email to ${user.email}: Automation ${auto.name} fired on ${triggerEvent}`);
          }
        }
      }
    }
  } catch (error) {
    console.error("Automation execution failed:", error);
  }
}
